version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    #ports:
    #  - "3000:3000"      

  postgres:
    image: postgres
    container_name: "postgres-test"
    restart: always   
    environment:
      POSTGRES_DB: test_smartsoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database-data:/var/lib/postgresql/data/    
    #ports:
    # - 5432:5432

  nginx:
    image: nginx
    container_name: "nginx-test"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on: 
      - app
    links: 
      - app
     