version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    depends_on:
      - redis
    volumes:
      - .:/app
    restart: always
    command: npm run dev
    #ports:
    #  - "3000:3000"     

  postgres:
    image: postgres
    container_name: "postgres-test"
    restart: always   
    environment:
      POSTGRES_DB: test_smartsoft
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data/    
    #ports:
    # - 5432:5432

  nginx:
    image: nginx
    container_name: "nginx-test"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on: 
      - app
    links: 
      - app

  redis:
    image: redis    
    #ports: 
    #  - 6379:6379    

     